name: demetra  
title: Demetra 
version: '0.1'
summary: A todo app made with flutter and yaru 
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

source-code: https://github.com/peter-kal/demetra
issues: https://github.com/peter-kal/demetra/issues 

base: core22 
grade: devel 
confinement: devmode 
compression: lzo

slots:
  demetra-dbus:
    interface: dbus
    bus: session 
    name: io.peter_kal.Demetra


apps:
 demetra: 
   command: demetra
   extensions: [gnome]
   plugs:
    - x11
    - wayland
    - unity7
    - desktop 
    - desktop-legacy 
    - opengl 
    
    
parts:
  demetra:
    plugin: flutter
    source-type: git
    source: https://github.com/peter-kal/demetra
    flutter-target: lib/main.dart
